#!/usr/bin/env bash
# scripts/setup-server-oci.sh
# One-time bootstrap for a fresh Oracle Cloud (OCI) Ubuntu 22.04 instance.
#
# Why this exists separately from setup-server.sh (DigitalOcean):
#   1. SSH user is 'ubuntu', not 'root' — OCI images disable root login.
#   2. OCI Ubuntu images ship iptables rules that REJECT every inbound port
#      except 22. Opening a port in the VCN Security List is NOT enough; the
#      instance itself still drops the traffic. This is the #1 reason an OCI
#      site is unreachable "even though the firewall is open".
#   3. No UFW. Docker publishes ports via DNAT and bypasses UFW anyway, and
#      stacking UFW on top of Oracle's iptables rules hides the real problem.
#      The VCN Security List is the perimeter firewall; iptables here just
#      stops Oracle's default REJECT from blocking Docker.
#
# Usage (on the OCI instance):
#   ssh -i ~/eshop_key ubuntu@<PUBLIC_IP>
#   sudo bash /opt/eshop/scripts/setup-server-oci.sh
# or, before the repo is cloned:
#   curl -fsSL https://raw.githubusercontent.com/geethashankar1/onlinestore/main/scripts/setup-server-oci.sh | sudo bash

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/geethashankar1/onlinestore.git}"
APP_DIR="/opt/eshop"
DEPLOY_USER="${SUDO_USER:-ubuntu}"

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: run with sudo — e.g. 'sudo bash $0'" >&2
  exit 1
fi

echo "======================================================"
echo " My E-Shop — OCI Server Bootstrap"
echo " Deploy user: $DEPLOY_USER   Arch: $(uname -m)"
echo "======================================================"

# ── 1. Install Docker ─────────────────────────────────────────
echo ""
echo "▶ Installing Docker…"
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sh
else
  echo "   Docker already present — skipping install."
fi
systemctl enable --now docker

if ! docker compose version &>/dev/null; then
  apt-get install -y docker-compose-plugin
fi

# Let the login user run docker without sudo (takes effect on next login)
usermod -aG docker "$DEPLOY_USER"

echo "   $(docker --version)"
echo "   $(docker compose version)"

# ── 2. Open the ports Oracle's default iptables rules block ───
# Oracle's INPUT chain ends in a catch-all REJECT, so new rules MUST be
# inserted above it (-I), not appended (-A) where they would never be reached.
echo ""
echo "▶ Opening ports 80, 443, 8080, 8090 in iptables…"
BACKUP="/root/iptables-backup-$(date +%F-%H%M%S).rules"
iptables-save > "$BACKUP"
echo "   Existing rules backed up to $BACKUP"

for port in 80 443 8080 8090; do
  if iptables -C INPUT -p tcp --dport "$port" -j ACCEPT 2>/dev/null; then
    echo "   Port $port already allowed."
  else
    iptables -I INPUT 1 -p tcp --dport "$port" -j ACCEPT
    echo "   Port $port opened."
  fi
done

# Docker's bridge networking routes container traffic through FORWARD.
# Oracle's catch-all REJECT there breaks published container ports.
while iptables -C FORWARD -j REJECT --reject-with icmp-host-prohibited 2>/dev/null; do
  iptables -D FORWARD -j REJECT --reject-with icmp-host-prohibited
  echo "   Removed catch-all REJECT from FORWARD (needed for Docker)."
done

echo ""
echo "▶ Persisting iptables rules across reboots…"
DEBIAN_FRONTEND=noninteractive apt-get install -y iptables-persistent netfilter-persistent
netfilter-persistent save
echo "   Rules saved."

# ── 3. App directory + repo ───────────────────────────────────
echo ""
echo "▶ Setting up $APP_DIR…"
if [[ -d "$APP_DIR/.git" ]]; then
  echo "   Repo already cloned — pulling latest."
  git -C "$APP_DIR" pull --ff-only || echo "   (pull skipped — local changes present)"
else
  apt-get install -y git
  mkdir -p "$APP_DIR"
  git clone "$REPO_URL" "$APP_DIR"
fi
chown -R "$DEPLOY_USER":"$DEPLOY_USER" "$APP_DIR"
echo "   $APP_DIR ready."

# ── 4. Generate .env with fresh secrets (only if missing) ─────
echo ""
echo "▶ Checking $APP_DIR/.env…"
if [[ -f "$APP_DIR/.env" ]]; then
  echo "   .env already exists — leaving it untouched."
else
  gen() { openssl rand -base64 24 | tr -d '/+=' | head -c 24; }
  cat > "$APP_DIR/.env" <<EOF
# Generated by setup-server-oci.sh on $(date -u +%F" "%T) UTC
# Production image pulled from GHCR by docker-compose.prod.yml
WEB_IMAGE=ghcr.io/geethashankar1/onlinestore:latest

# ── Production database ──────────────────────────────────────
DB_NAME=ecommerce_db
DB_USER=eshop
DB_PASS=$(gen)
DB_ROOT_PASS=$(gen)

# ── Staging database ─────────────────────────────────────────
STAGING_DB_NAME=ecommerce_db_staging
STAGING_DB_USER=eshop_staging
STAGING_DB_PASS=$(gen)
STAGING_DB_ROOT_PASS=$(gen)

# ── Payment gateways — fill these in before going live ───────
AUTHNET_LOGIN_ID=
AUTHNET_TRANS_KEY=
AUTHNET_CLIENT_KEY=
AUTHNET_SANDBOX=true
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
RAZORPAY_CURRENCY=INR
EOF
  chown "$DEPLOY_USER":"$DEPLOY_USER" "$APP_DIR/.env"
  chmod 600 "$APP_DIR/.env"
  echo "   .env created with generated DB passwords (chmod 600)."
  echo "   View them with:  sudo cat $APP_DIR/.env"
fi

# ── 5. Nightly nginx reload so renewed certs are picked up ────
echo ""
echo "▶ Installing certbot renewal cron…"
CRON_LINE="0 3 * * * docker exec eshop_nginx nginx -s reload"
( crontab -l 2>/dev/null | grep -Fv "eshop_nginx nginx -s reload"; echo "$CRON_LINE" ) | crontab -
echo "   Cron installed (nginx reload nightly at 03:00)."

# ── Done ──────────────────────────────────────────────────────
cat <<EOF

======================================================
 Bootstrap complete.

 Next steps:
  1. Log out and back in so docker group membership applies:
       exit   &&   ssh -i ~/eshop_key $DEPLOY_USER@<PUBLIC_IP>

  2. Fill in payment keys (optional for first boot):
       nano $APP_DIR/.env

  3. Start Jenkins:
       cd $APP_DIR
       docker compose -f docker-compose.jenkins.yml up -d
       docker exec eshop_jenkins cat /var/jenkins_home/secrets/initialAdminPassword
     Then open  http://<PUBLIC_IP>:8090

  4. Point DNS at this server, then issue SSL:
       bash $APP_DIR/scripts/ssl-init.sh myeshopstore.online you@example.com

 Full runbook: $APP_DIR/DEPLOY_OCI.md
======================================================
EOF
